/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package organized.books;

import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Antonio
 */

//esta clase auxiliar permite ayudarnos a añadir componenetes Clase_componente para usarlos en el vector de Clase_contenedor
public class Clase_contenedor extends javax.swing.JPanel {

    /**
     * Creates new form clase_contenedor
     * @param libro_encontrado
     */
    ArrayList<Integer> v_librosId = new ArrayList();
    ArrayList<JButton> botoneslibros = new ArrayList();
    
    public Clase_contenedor() {
        initComponents();
       
    }
    
    public ArrayList<Integer> getV_librosId() {
        return v_librosId;
    }
    
    public ArrayList<JButton> getV_botoneslibros() {
        return botoneslibros;
    }
    
    public void nuevo_componente(organized.books.Componente_lbr libro_encontrado){
        this.add(libro_encontrado);
        this.setVisible(false);
        v_librosId.add(libro_encontrado.getId());
        botoneslibros.add(libro_encontrado.btn_NombreAutor_libro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(1090, 403));
        setMinimumSize(new java.awt.Dimension(1090, 403));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1090, 403));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
