/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package organized.books;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;

/**
 *
 * @author Antonio
 */

//componente que simula un libro abriendose
public class componente_Carga extends javax.swing.JPanel {

    /**
     * Creates new form componente_Carga
     */
    
    int valor=0;
    public componente_Carga(){
        initComponents();
        
        int velocidadmil = 500;
        
        Timer timer;
        TimerTask tarea;
        
        tarea = new TimerTask(){
            
            public void run(){
                valor++;
                if(valor>=3){
                    
                    valor=0;
                }
                contenedor.setIcon(new ImageIcon(getClass().getResource("/imagenes/libroEstado"+valor+".png"))); 
            }          
            
        };
        timer = new Timer();
        //tarea que se realiza, cuando empieza a realizarse y cada cuanto se realiza
        timer.scheduleAtFixedRate(tarea, velocidadmil, velocidadmil);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(128, 128));
        setMinimumSize(new java.awt.Dimension(128, 128));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(128, 128));

        contenedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contenedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libroEstado0.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contenedor;
    // End of variables declaration//GEN-END:variables
}
