/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package organized.books;

import javax.swing.JButton;



/**
 *
 * @author Antonio
 */

//clase que contiene la interfaz para Modificar un Ebook
public class ModificarLibroEbook extends javax.swing.JPanel {
    
    /**
     * Creates new form VerLibroFísico
     */
    
    
    ComponenteNota comp_nota = new ComponenteNota();
    int _id;
  
    public ModificarLibroEbook() {
        initComponents();
    }
    
    public ModificarLibroEbook(int id) {
        initComponents();

        Libro libro_para_ver = Bd.libro_Por_ID(id, 1);
        campo_autor.setText(libro_para_ver.getAutor());
        campo_nombre.setText(libro_para_ver.getNombre_libro());
        campo_resumen.setText(libro_para_ver.getResumen());
         
        comp_nota = new ComponenteNota(libro_para_ver.getOpinion());
        comp_nota.setSize(242, 171);
        comp_nota.setLocation(159,245); 
        contenedor.add(comp_nota);
        contenedor.setVisible(true);
        _id=id;
        }

    public JButton getBtn_aceptaModificacionLibro() {
        return btn_aceptaModificacionLibro;
    }

    public JButton getBtn_BorrarLibro() {
        return btn_BorrarLibro;
    }

    public boolean hayError(){
        return campo_autor.getText().isEmpty()||campo_nombre.getText().isEmpty()||campo_resumen.getText().isEmpty();
    }
    
    public void ModificarLibro(){
        Libro libro_elegido = new Libro(_id, campo_nombre.getText(), campo_autor.getText(), campo_resumen.getText(),"", comp_nota.getNota());
        Bd.ModificarLibro(_id, libro_elegido, 1);
    }

    public int getId() {
        return _id;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new FondoPanel(3);
        label_autor = new javax.swing.JLabel();
        label_resumen = new javax.swing.JLabel();
        label_titulo = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        campo_autor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_resumen = new javax.swing.JTextArea();
        label_nota = new javax.swing.JLabel();
        btn_aceptaModificacionLibro = new javax.swing.JButton();
        btn_BorrarLibro = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1090, 500));
        setMinimumSize(new java.awt.Dimension(1090, 500));
        setPreferredSize(new java.awt.Dimension(1090, 500));

        contenedor.setMaximumSize(new java.awt.Dimension(1090, 500));
        contenedor.setMinimumSize(new java.awt.Dimension(1090, 500));
        contenedor.setPreferredSize(new java.awt.Dimension(1090, 500));

        label_autor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label_autor.setText("Autor/a");

        label_resumen.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label_resumen.setText("Resumen:");

        label_titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label_titulo.setText("Título:");

        campo_nombre.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        campo_nombre.setText("jTextField1");
        campo_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campo_autor.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        campo_autor.setText("jTextField1");
        campo_autor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campo_resumen.setColumns(20);
        campo_resumen.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        campo_resumen.setLineWrap(true);
        campo_resumen.setRows(5);
        campo_resumen.setWrapStyleWord(true);
        campo_resumen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(campo_resumen);

        label_nota.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label_nota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nota.setText("Nota:");

        btn_aceptaModificacionLibro.setBackground(new java.awt.Color(153, 102, 0));
        btn_aceptaModificacionLibro.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btn_aceptaModificacionLibro.setText("Aceptar");
        btn_aceptaModificacionLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_aceptaModificacionLibro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btn_BorrarLibro.setBackground(new java.awt.Color(153, 102, 0));
        btn_BorrarLibro.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btn_BorrarLibro.setText("Borrar Libro");
        btn_BorrarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_BorrarLibro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campo_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(label_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                        .addComponent(label_resumen, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_BorrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(btn_aceptaModificacionLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_resumen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(label_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(campo_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(label_nota))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptaModificacionLibro)
                    .addComponent(btn_BorrarLibro))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BorrarLibro;
    private javax.swing.JButton btn_aceptaModificacionLibro;
    private javax.swing.JTextField campo_autor;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextArea campo_resumen;
    private javax.swing.JPanel contenedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_autor;
    private javax.swing.JLabel label_nota;
    private javax.swing.JLabel label_resumen;
    private javax.swing.JLabel label_titulo;
    // End of variables declaration//GEN-END:variables
}
