/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package organized.books;

import javax.swing.JButton;

/**
 *
 * @author Antonio
 */

 //clase para ver un Libro Fisico
public class VerLibroFisico extends javax.swing.JPanel {
    
    /**
     * Creates new form VerLibroFísico
     */
    
    Libro libro_elegido = new Libro();
    int _id;
    
    public VerLibroFisico() {
        initComponents();
    }
    
    public VerLibroFisico(int id) {
        initComponents();

        Libro libro_para_ver = Bd.libro_Por_ID(id, 0);
        campo_autor.setText(libro_para_ver.getAutor());
        campo_lugar.setText(libro_para_ver.getLugar());
        campo_nombre.setText(libro_para_ver.getNombre_libro());
        campo_resumen.setText(libro_para_ver.getResumen());
        campo_nota.setText(String.valueOf(libro_para_ver.getOpinion()));
        _id=id;
    }

    public JButton getBoton_modificar_librof() {
        return boton_modificar_librof;
    }
    public int getId() {
        return _id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new FondoPanel(3);
        label_autor = new javax.swing.JLabel();
        campo_lugar = new javax.swing.JTextField();
        label_resumen = new javax.swing.JLabel();
        label_titulo = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        label_lugar = new javax.swing.JLabel();
        campo_autor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_resumen = new javax.swing.JTextArea();
        label_nota = new javax.swing.JLabel();
        campo_nota = new javax.swing.JLabel();
        boton_modificar_librof =  new FondoBoton(5);

        setMaximumSize(new java.awt.Dimension(1090, 500));
        setMinimumSize(new java.awt.Dimension(1090, 500));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1090, 500));

        contenedor.setMaximumSize(new java.awt.Dimension(1090, 500));
        contenedor.setMinimumSize(new java.awt.Dimension(1090, 500));
        contenedor.setOpaque(false);
        contenedor.setPreferredSize(new java.awt.Dimension(1090, 500));

        label_autor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label_autor.setText("Autor/a");

        campo_lugar.setEditable(false);
        campo_lugar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        campo_lugar.setText("jTextField1");
        campo_lugar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_resumen.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label_resumen.setText("Resumen:");

        label_titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label_titulo.setText("Título:");

        campo_nombre.setEditable(false);
        campo_nombre.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        campo_nombre.setText("jTextField1");
        campo_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_lugar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label_lugar.setText("Lugar");

        campo_autor.setEditable(false);
        campo_autor.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        campo_autor.setText("jTextField1");
        campo_autor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campo_resumen.setEditable(false);
        campo_resumen.setColumns(20);
        campo_resumen.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        campo_resumen.setLineWrap(true);
        campo_resumen.setRows(5);
        campo_resumen.setWrapStyleWord(true);
        campo_resumen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(campo_resumen);

        label_nota.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label_nota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nota.setText("Nota:");

        campo_nota.setFont(new java.awt.Font("Comic Sans MS", 1, 100)); // NOI18N
        campo_nota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo_nota.setText("0");

        boton_modificar_librof.setToolTipText("");
        boton_modificar_librof.setBorder(null);
        boton_modificar_librof.setBorderPainted(false);
        boton_modificar_librof.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_modificar_librof.setMaximumSize(new java.awt.Dimension(64, 64));
        boton_modificar_librof.setMinimumSize(new java.awt.Dimension(64, 64));
        boton_modificar_librof.setOpaque(false);
        boton_modificar_librof.setPreferredSize(new java.awt.Dimension(64, 64));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campo_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(label_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(campo_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                        .addComponent(boton_modificar_librof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                        .addComponent(label_resumen, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boton_modificar_librof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_resumen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(campo_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_nota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_modificar_librof;
    private javax.swing.JTextField campo_autor;
    private javax.swing.JTextField campo_lugar;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JLabel campo_nota;
    private javax.swing.JTextArea campo_resumen;
    private javax.swing.JPanel contenedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_autor;
    private javax.swing.JLabel label_lugar;
    private javax.swing.JLabel label_nota;
    private javax.swing.JLabel label_resumen;
    private javax.swing.JLabel label_titulo;
    // End of variables declaration//GEN-END:variables
}
