# Target specific macros
TARGET = practica_3explorador
TARGET_SOURCES := \
	practica_3explorador.c
TOPPERS_OSEK_OIL_SOURCE := ./practica_3explorador.oil

O_PATH ?= build

include ../../ecrobot/ecrobot.mak
